#!/bin/sh

git clone https://github.com/xaverdh/posix-fd-io
git clone https://github.com/xaverdh/nfc-text
git clone https://github.com/xaverdh/hfish
git clone https://github.com/xaverdh/hfish-parser
git clone https://github.com/xaverdh/fish-parser
git clone https://github.com/xaverdh/fish-lang
cd hfish
cabal sandbox init
cabal sandbox add-source ../posix-fd-io ../nfc-text ../fish-lang ../fish-parser ../hfish-parser
command -v sed > /dev/null && sed -i -E \
  's/^[[:space:]]*version[[:space:]]*=[[:space:]]*".*"$/version = "'$(git log -1 --pretty=format:%H)'"/' \
  HFish/Interpreter/Version.hs
cabal install --ghc-option=-threaded

