#!/bin/sh

git clone https://gitlab.com/hfish-shell/posix-fd-io
git clone https://gitlab.com/hfish-shell/nfc-text
git clone https://gitlab.com/hfish-shell/hfish
git clone https://gitlab.com/hfish-shell/hfish-parser
git clone https://gitlab.com/hfish-shell/fish-parser
git clone https://gitlab.com/hfish-shell/fish-lang
cd hfish
cabal sandbox init
cabal sandbox add-source ../posix-fd-io ../nfc-text ../fish-lang ../fish-parser ../hfish-parser
command -v sed > /dev/null && sed -i -E \
  's/^[[:space:]]*version[[:space:]]*=[[:space:]]*".*"$/version = "'$(git log -1 --pretty=format:%H)'"/' \
  HFish/Interpreter/Version.hs
cabal install --ghc-option=-threaded

