#!/bin/sh

git clone git://github.com/xaverdh/posix-fd-io
git clone git://github.com/xaverdh/nfc-text
git clone git://github.com/xaverdh/hfish
git clone git://github.com/xaverdh/hfish-parser
git clone git://github.com/xaverdh/fish-parser
git clone git://github.com/xaverdh/fish-lang
cd hfish
cabal sandbox init
cabal sandbox add-source ../posix-fd-io ../nfc-text ../fish-lang ../fish-parser ../hfish-parser
cabal install --ghc-option=-threaded

